"""initial_schema

Revision ID: 13f9089c7e5f
Revises: 
Create Date: 2026-03-10 06:31:47.504056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f9089c7e5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('source', sa.Enum('LINKEDIN', 'INDEED', 'NAUKRI', 'COMPANY_CAREER', 'OTHER', name='jobsource'), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_job_id', sa.String(length=255), nullable=True),
    sa.Column('company_logo_url', sa.String(length=1000), nullable=True),
    sa.Column('role_level', sa.String(length=50), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('company_type', sa.String(length=50), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_reasoning', sa.Text(), nullable=True),
    sa.Column('extracted_keywords', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index(op.f('ix_job_listings_company'), 'job_listings', ['company'], unique=False)
    op.create_index(op.f('ix_job_listings_source'), 'job_listings', ['source'], unique=False)
    op.create_index(op.f('ix_job_listings_user_id'), 'job_listings', ['user_id'], unique=False)
    op.create_table('resume_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('latex_source', sa.Text(), nullable=False),
    sa.Column('preview_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portfolio_url', sa.String(length=500), nullable=True),
    sa.Column('encrypted_linkedin_creds', sa.Text(), nullable=True),
    sa.Column('encrypted_indeed_creds', sa.Text(), nullable=True),
    sa.Column('encrypted_naukri_creds', sa.Text(), nullable=True),
    sa.Column('master_resume_latex', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_module'), 'audit_logs', ['module'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('recruiters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_listing_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('profile_image_url', sa.String(length=1000), nullable=True),
    sa.Column('connection_status', sa.Enum('NOT_CONNECTED', 'PENDING', 'CONNECTED', 'BLOCKED', name='connectionstatus'), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_url')
    )
    op.create_index(op.f('ix_recruiters_user_id'), 'recruiters', ['user_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('latex_source', sa.Text(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('pdf_s3_key', sa.String(length=500), nullable=True),
    sa.Column('pdf_file_size', sa.Integer(), nullable=True),
    sa.Column('compilation_status', sa.String(length=50), nullable=False),
    sa.Column('compilation_errors', sa.Text(), nullable=True),
    sa.Column('target_company', sa.String(length=255), nullable=True),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('focus_area', sa.String(length=255), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.Column('tailored_for_job_id', sa.UUID(), nullable=True),
    sa.Column('ai_tailored', sa.Boolean(), nullable=False),
    sa.Column('ai_prompt_used', sa.Text(), nullable=True),
    sa.Column('ai_changes_summary', sa.Text(), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tailored_for_job_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['resume_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_user_id'), 'resume_versions', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_listing_id', sa.UUID(), nullable=False),
    sa.Column('resume_version_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=500), nullable=False),
    sa.Column('job_description_snapshot', sa.Text(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPLYING', 'APPLIED', 'VIEWED', 'INTERVIEW', 'OFFER', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('method', sa.Enum('MANUAL', 'AUTOMATED', 'REFERRAL', name='applicationmethod'), nullable=False),
    sa.Column('automation_log', sa.Text(), nullable=True),
    sa.Column('automation_error', sa.Text(), nullable=True),
    sa.Column('form_data_snapshot', sa.Text(), nullable=True),
    sa.Column('applied_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_listing_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['resume_version_id'], ['resume_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_company'), 'applications', ['company'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_table('outreach_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'REPLIED', 'FAILED', name='outreachstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_messages_user_id'), 'outreach_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_messages_user_id'), table_name='outreach_messages')
    op.drop_table('outreach_messages')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_company'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_resume_versions_user_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_recruiters_user_id'), table_name='recruiters')
    op.drop_table('recruiters')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_module'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('resume_templates')
    op.drop_index(op.f('ix_job_listings_user_id'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_source'), table_name='job_listings')
    op.drop_index(op.f('ix_job_listings_company'), table_name='job_listings')
    op.drop_table('job_listings')
    # ### end Alembic commands ###
