"""make_resume_version_id_nullable

Revision ID: 6159f7dbe8e8
Revises: a2b3c4d5e6f7
Create Date: 2026-03-20 20:21:21.871226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6159f7dbe8e8'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'resume_version_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'resume_version_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
