"""add_gmail_refresh_token

Revision ID: a87f2aeb629d
Revises: a3b7c9d1e2f4
Create Date: 2026-03-18 14:52:44.679323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87f2aeb629d'
down_revision: Union[str, None] = 'a3b7c9d1e2f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_agent_name'), 'agent_executions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_executions_user_id'), 'agent_executions', ['user_id'], unique=False)
    op.create_table('email_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=False),
    sa.Column('email_from', sa.String(length=255), nullable=False),
    sa.Column('email_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('raw_snippet', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_tracking_application_id'), 'email_tracking', ['application_id'], unique=False)
    op.create_index(op.f('ix_email_tracking_classification'), 'email_tracking', ['classification'], unique=False)
    op.create_index(op.f('ix_email_tracking_user_id'), 'email_tracking', ['user_id'], unique=False)
    op.add_column('job_listings', sa.Column('estimated_salary_breakdown', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gmail_refresh_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmail_refresh_token')
    op.drop_column('job_listings', 'estimated_salary_breakdown')
    op.drop_index(op.f('ix_email_tracking_user_id'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_classification'), table_name='email_tracking')
    op.drop_index(op.f('ix_email_tracking_application_id'), table_name='email_tracking')
    op.drop_table('email_tracking')
    op.drop_index(op.f('ix_agent_executions_user_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_name'), table_name='agent_executions')
    op.drop_table('agent_executions')
    # ### end Alembic commands ###
