"""add_job_search_preferences

Revision ID: fed9a23be6a2
Revises: 1e2857a4e341
Create Date: 2026-03-10 13:40:22.138047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fed9a23be6a2'
down_revision: Union[str, None] = '1e2857a4e341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('job_search_keywords', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('preferred_location', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_location')
    op.drop_column('users', 'job_search_keywords')
    # ### end Alembic commands ###
